//import type { Metadata } from "next";
//import { Inter } from "next/font/google";
//import "./app.css";

//const inter = Inter({ subsets: ["latin"] });

//export const metadata: Metadata = {
  //title: "Create Next App",
  //description: "Generated by create next app",
//};

//export default function RootLayout({
  //children,
//}: {
  //children: React.ReactNode;
//}) {
  //return (
    //<html lang="en">
      //<body className={inter.className}>{children}</body>
    //</html>
  ///);
//}


import React, { ReactNode } from 'react';
import Sidebar from './Sidebar';

interface LayoutProps {
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div style={{ display: 'flex' }}>
      <Sidebar />
      <main style={{ flex: 1, padding: '20px' }}>
        {children}
      </main>
    </div>
  );
};

export default Layout;