//import type { Metadata } from "next";
//import { Inter } from "next/font/google";
//import "./app.css";

//const inter = Inter({ subsets: ["latin"] });

//export const metadata: Metadata = {
  //title: "Create Next App",
  //description: "Generated by create next app",
//};

//export default function RootLayout({
  //children,
//}: {
  //children: React.ReactNode;
//}) {
  //return (
    //<html lang="en">
      //<body className={inter.className}>{children}</body>
    //</html>
  ///);
//}


"use client";

import React, { useEffect, useState, ReactNode } from 'react';
import Sidebar from './Sidebar';

interface LayoutProps {
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  if (!isClient) {
    return null; // クライアントサイドでのみレンダリングする要素を避ける
  }


  //Next.jsのルートレイアウトに<html>および<body>タグが含まれていないとエラーが発生する。

  return (
    <html lang="en">
      <body>
        <div style={{ display: 'flex' }}>
          <Sidebar />
          <main style={{ flex: 1, padding: '20px' }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
};

export default Layout;